# Generated by Django 5.0.2 on 2026-06-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_patienttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('transferred', 'Transferred'), ('released', 'Released'), ('deceased', 'Deceased')], default='admitted', max_length=100),
        ),
    ]
