# Generated by Django 5.0.2 on 2026-07-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
