# Generated by Django 5.0.2 on 2026-07-19 06:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_remove_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingcomplaint',
            name='age',
        ),
        migrations.RemoveField(
            model_name='missingcomplaint',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='missingcomplaint',
            name='person_name',
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='clothing_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='height',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='identifying_marks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='missing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='missing_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Searching', 'Searching'), ('Found', 'Found'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='missingcomplaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='contact_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='hazard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_complaints', to='Core.hazardreport'),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='last_seen_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_person_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_person_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_person_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_complaints', to='Core.patient'),
        ),
    ]
