# Generated by Django 5.0.2 on 2026-07-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_profile_profile_image_user_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0)),
                ('face_verified', models.BooleanField(default=False)),
                ('face_distance', models.FloatField(default=1.0)),
                ('match_status', models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='Core.missingcomplaint')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='Core.patient')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
    ]
