# Generated by Django 5.0.2 on 2026-07-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_patientmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
