# Generated by Django 5.0.2 on 2026-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingcomplaint',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimeters', null=True),
        ),
    ]
