# Generated by Django 5.0.2 on 2026-07-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_alter_missingcomplaint_height_alter_patient_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmatch',
            name='match_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
