# Generated by Django 5.0.2 on 2026-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_patientmatch_confirmed_patientmatch_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmatch',
            name='age_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientmatch',
            name='age_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientmatch',
            name='blood_group_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientmatch',
            name='gender_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientmatch',
            name='height_difference',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patientmatch',
            name='height_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientmatch',
            name='name_similarity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in feet (e.g. 5.6)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in feet (e.g. 5.6)', max_digits=3, null=True),
        ),
    ]
