# Generated by Django 5.0.2 on 2026-07-21 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_patientmatch_age_difference_patientmatch_age_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clothing_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='identifying_marks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='clothing_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='identifying_marks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='last_seen_location',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_person_age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_person_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_person_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='missing_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], default='Other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='missingcomplaint',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Searching', 'Searching'), ('Found', 'Found'), ('Closed', 'Closed')], default='Pending', max_length=20, null=True),
        ),
    ]
