# Generated by Django 5.0.2 on 2026-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_patient_clothing_description_patient_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
