# Generated by Django 5.0.2 on 2026-08-12 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_alter_patient_age_alter_patient_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_identified',
            field=models.BooleanField(default=False),
        ),
    ]
