# Generated by Django 5.0.2 on 2026-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ambulances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='desscription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_departments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_doctors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_nurses',
            field=models.IntegerField(default=0),
        ),
    ]
