# Generated by Django 5.0.2 on 2026-08-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_hospital_ambulances_hospital_desscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='desscription',
            new_name='description',
        ),
    ]
