# Generated by Django 5.0.2 on 2026-08-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_rename_desscription_hospital_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'permissions': [('view_hospital_dashboard', 'Can view hospital dashboard')]},
        ),
    ]
