# Generated by Django 5.0.2 on 2026-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_alter_hospital_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='Core.hospital'),
        ),
    ]
