# Generated by Django 5.0.2 on 2026-08-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_user_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazard_reports', to='Core.hospital'),
        ),
    ]
