# Generated by Django 5.0.2 on 2026-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_hazardreport_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardreport',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='hazards', to='Core.hospital'),
        ),
    ]
