# Generated by Django 5.0.2 on 2026-08-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_remove_hazardreport_hospital_hazardreport_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
