# Generated by Django 5.0.2 on 2026-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0037_hazardreport_latitude_hazardreport_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
