# Generated by Django 5.0.2 on 2026-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0041_firestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fire_stations/'),
        ),
    ]
