# Generated by Django 5.0.2 on 2026-09-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_firestation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='official_website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
