# Generated by Django 5.0.2 on 2026-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0043_hospital_latitude_hospital_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_for_donation',
            field=models.BooleanField(default=False),
        ),
    ]
