# Generated by Django 5.0.2 on 2026-09-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0047_repair_user_role_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='ambulances',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_departments',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_doctors',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_nurses',
        ),
    ]
