# Generated by Django 5.0.2 on 2026-09-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0049_alter_notification_notification_type'),
        ('Core', '0051_repair_patient_identified_by_users'),
    ]

    operations = [
    ]
